apiVersion: v1
kind: Service
metadata:
  name: muita-conta-front-service
  namespace: muita-conta-front 
  labels:
    app: muita-conta-front
spec:
  selector:
    app: muita-conta-front
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP